name: Create and publish an OCI image

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Determine next version and push tag
        id: semantic-release
        uses: codfish/semantic-release-action@v3
        with:
          tag-format: 'v${version}'
          branches: |
            [ 'feature/containerize', 'master' ]
          plugins: |
            ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', '@semantic-release/github']
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the container registry (GitHub packages)
        if: steps.semantic-release.outputs.new-release-published == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        if: steps.semantic-release.outputs.new-release-published == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Set version tag based on semantic release output
            type=semver,pattern=v{{version}},value=${{ steps.semantic-release.outputs.release-version }}
            # Set latest tag
            type=raw,value=latest

      - name: Build and push Docker image
        if: steps.semantic-release.outputs.new-release-published == 'true'
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
